### PR TITLE
Ian

### PR DESCRIPTION
**Pull request by IanChar**
This is a basic page that tells what sensors are currently on. As of now, if you touch the screen a new sensor will appear (up to 8). This will undoubtedly not be a feature in the final build but I wanted to test adding new sensors to the list. In this branch I structured the page using XML. I also made another branch where I tried to do it purely in Javascript but I ran into some problems; however, in the future that may be the way to go.

### CODE REVIEW

**Comment by derekriemer** [comment]
Hey Ian.
Do you mind doing your code in branches?
It makes it really easy to know where a tickets code is if it is all in 
a branch with the letter t, followed by the issue name. Of course there 
are reasons not to, say you have an issue, but make sure you mark down 
as a branch on the issue, I.E. The code is in branch sensor_testing_ui
Thanks,
Derek
On 8/31/2014 10:38 AM, Ian wrote:

> This is a basic page that tells what sensors are currently on. As of 
> now, if you touch the screen a new sensor will appear (up to 8). This 
> will undoubtedly not be a feature in the final build but I wanted to 
> test adding new sensors to the list. In this branch I structured the 
> page using XML. I also made another branch where I tried to do it 
> purely in Javascript but I ran into some problems; however, in the 
> future that may be the way to go.
> 
> ---
> 
> ```
>     You can merge this Pull Request by running
> ```
> 
>    git pull https://github.com/derekriemer/uist2014_colo ian
> 
> Or view, comment on, or merge it at:
> 
> https://github.com/derekriemer/uist2014_colo/pull/5
> 
> ```
>     Commit Summary
> ```
> - Finished basic layout of the home screen
> - Simplified some of the layout and added text
> - Made it so when the screen is touched sensors are added. This will
>   probably change in the future but I wanted to see if I could do it.
>   
>   ```
>   File Changes
>   ```
> - _M_ src/main.xml
>   https://github.com/derekriemer/uist2014_colo/pull/5/files#diff-0
>   (48)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/derekriemer/uist2014_colo/pull/5.patch
> - https://github.com/derekriemer/uist2014_colo/pull/5.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/derekriemer/uist2014_colo/pull/5.

## 

---

```
Derek Riemer
```

Department of Computer science Undergrad, proud CILA member, music 
lover, and much more.

"Not everything that is faced can be changed, but nothing can be changed 
until it is faced." - James Baldwin

email me at derek.riemer@colorado.edu mailto:derek.riemer@colorado.edu
Phone: (303) 906-2194

**Comment by derekriemer** [comment]
Hey Ian. I just got the code pulled, and I will push it out so that 
Jackie has it.

On 8/31/2014 10:38 AM, Ian wrote:

> This is a basic page that tells what sensors are currently on. As of 
> now, if you touch the screen a new sensor will appear (up to 8). This 
> will undoubtedly not be a feature in the final build but I wanted to 
> test adding new sensors to the list. In this branch I structured the 
> page using XML. I also made another branch where I tried to do it 
> purely in Javascript but I ran into some problems; however, in the 
> future that may be the way to go.
> 
> ---
> 
> ```
>     You can merge this Pull Request by running
> ```
> 
>    git pull https://github.com/derekriemer/uist2014_colo ian
> 
> Or view, comment on, or merge it at:
> 
> https://github.com/derekriemer/uist2014_colo/pull/5
> 
> ```
>     Commit Summary
> ```
> - Finished basic layout of the home screen
> - Simplified some of the layout and added text
> - Made it so when the screen is touched sensors are added. This will
>   probably change in the future but I wanted to see if I could do it.
>   
>   ```
>   File Changes
>   ```
> - _M_ src/main.xml
>   https://github.com/derekriemer/uist2014_colo/pull/5/files#diff-0
>   (48)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/derekriemer/uist2014_colo/pull/5.patch
> - https://github.com/derekriemer/uist2014_colo/pull/5.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/derekriemer/uist2014_colo/pull/5.

## 

---

```
Derek Riemer
```

Department of Computer science Undergrad, proud CILA member, music 
lover, and much more.

"Not everything that is faced can be changed, but nothing can be changed 
until it is faced." - James Baldwin

email me at derek.riemer@colorado.edu mailto:derek.riemer@colorado.edu
Phone: (303) 906-2194

**Comment by IanChar** [comment]
Hey Derek,
Not sure if I am getting what you are asking completely. The code that I have for the merge request is in a branch. Did you just want me to rename the branch so that it matches an issue?

**Comment by derekriemer** [comment]
nvm.
Hey. I can't get kinoma studio to switch to the correct workspace. How 
did you do this?
On 8/31/2014 12:09 PM, Ian wrote:

> Hey Derek,
> Not sure if I am getting what you are asking completely. The code that 
> I have for the merge request is in a branch. Did you just want me to 
> rename the branch so that it matches an issue?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/derekriemer/uist2014_colo/pull/5#issuecomment-53996173.

## 

---

```
Derek Riemer
```

Department of Computer science Undergrad, proud CILA member, music 
lover, and much more.

"Not everything that is faced can be changed, but nothing can be changed 
until it is faced." - James Baldwin

email me at derek.riemer@colorado.edu mailto:derek.riemer@colorado.edu
Phone: (303) 906-2194

**Comment by derekriemer** [comment]
The code for me trying to import this is being tested in 
testing_project_import. So I don't screw up your branch.

On 8/31/2014 12:09 PM, Ian wrote:

> Hey Derek,
> Not sure if I am getting what you are asking completely. The code that 
> I have for the merge request is in a branch. Did you just want me to 
> rename the branch so that it matches an issue?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/derekriemer/uist2014_colo/pull/5#issuecomment-53996173.

## 

---

```
Derek Riemer
```

Department of Computer science Undergrad, proud CILA member, music 
lover, and much more.

"Not everything that is faced can be changed, but nothing can be changed 
until it is faced." - James Baldwin

email me at derek.riemer@colorado.edu mailto:derek.riemer@colorado.edu
Phone: (303) 906-2194

**Comment by IanChar** [comment]
Alright. And I just added it to my workspace directory. However, when I was working with the examples I found that the project manager thing would not automatically discover it. So what I had to do was create a new project and then just copy and paste the source code into the new project.

**Comment by derekriemer** [comment]
Okay. I am currently trying out opening it with the import  wizard but 
in a separate branch so I don't muck things up.
On 8/31/2014 12:17 PM, Ian wrote:

> Alright. And I just added it to my workspace directory. However, when 
> I was working with the examples I found that the project manager thing 
> would not automatically discover it. So what I had to do was create a 
> new project and then just copy and paste the source code into the new 
> project.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/derekriemer/uist2014_colo/pull/5#issuecomment-53996414.

## 

---

```
Derek Riemer
```

Department of Computer science Undergrad, proud CILA member, music 
lover, and much more.

"Not everything that is faced can be changed, but nothing can be changed 
until it is faced." - James Baldwin

email me at derek.riemer@colorado.edu mailto:derek.riemer@colorado.edu
Phone: (303) 906-2194

**Comment by IanChar** [comment]
Alright don't worry about changing anything. If something gets screwed up I can just push again.

**Comment by derekriemer** [comment]
Ah. Go to the project explorer, right click. import project, from git. 
Then select URI, and then provide the necessary info. Then it will work.
On 8/31/2014 12:19 PM, Ian wrote:

> Alright don't worry about changing anything. If something gets screwed 
> up I can just push again.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/derekriemer/uist2014_colo/pull/5#issuecomment-53996502.

## 

---

```
Derek Riemer
```

Department of Computer science Undergrad, proud CILA member, music 
lover, and much more.

"Not everything that is faced can be changed, but nothing can be changed 
until it is faced." - James Baldwin

email me at derek.riemer@colorado.edu mailto:derek.riemer@colorado.edu
Phone: (303) 906-2194

**Comment by IanChar** [comment]
Oh I see sweet thanks for finding that out.

**Comment by derekriemer** [comment]
Okay. Do a git pull, and let me know if you now see a comment in the 
main.xml where you update the sensor count. This is where I will add a 
sound later today after I do some homework.
On 8/31/2014 12:27 PM, Ian wrote:

> Oh I see sweet thanks for finding that out.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/derekriemer/uist2014_colo/pull/5#issuecomment-53996720.

## 

---

```
Derek Riemer
```

Department of Computer science Undergrad, proud CILA member, music 
lover, and much more.

"Not everything that is faced can be changed, but nothing can be changed 
until it is faced." - James Baldwin

email me at derek.riemer@colorado.edu mailto:derek.riemer@colorado.edu
Phone: (303) 906-2194

**Comment by derekriemer** [comment]
What does the tag
<![CDATA[

Mean?

On 8/31/2014 12:09 PM, Ian wrote:

> Hey Derek,
> Not sure if I am getting what you are asking completely. The code that 
> I have for the merge request is in a branch. Did you just want me to 
> rename the branch so that it matches an issue?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/derekriemer/uist2014_colo/pull/5#issuecomment-53996173.

## 

---

```
Derek Riemer
```

Department of Computer science Undergrad, proud CILA member, music 
lover, and much more.

"Not everything that is faced can be changed, but nothing can be changed 
until it is faced." - James Baldwin

email me at derek.riemer@colorado.edu mailto:derek.riemer@colorado.edu
Phone: (303) 906-2194

**Pull request merged**
